// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYF9LwW3UfTKsp4mlekyuCHF_ra9ZlgTI',
    appId: '1:75537837422:web:918b636f8b9bbbfa04257f',
    messagingSenderId: '75537837422',
    projectId: 'blitzapp-a2a39',
    authDomain: 'blitzapp-a2a39.firebaseapp.com',
    storageBucket: 'blitzapp-a2a39.appspot.com',
    measurementId: 'G-X1P06YX2H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTX1Ko9rtRm8i3LNOD58zbEttbLqkJs4',
    appId: '1:75537837422:android:8c721ded6c02024c04257f',
    messagingSenderId: '75537837422',
    projectId: 'blitzapp-a2a39',
    storageBucket: 'blitzapp-a2a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjeZAGfAdB2KBuZT3ojaF7Z4J5QuXVpzY',
    appId: '1:75537837422:ios:eca848356d078f2104257f',
    messagingSenderId: '75537837422',
    projectId: 'blitzapp-a2a39',
    storageBucket: 'blitzapp-a2a39.appspot.com',
    iosBundleId: 'com.example.gradeProject1765532',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjeZAGfAdB2KBuZT3ojaF7Z4J5QuXVpzY',
    appId: '1:75537837422:ios:eca848356d078f2104257f',
    messagingSenderId: '75537837422',
    projectId: 'blitzapp-a2a39',
    storageBucket: 'blitzapp-a2a39.appspot.com',
    iosBundleId: 'com.example.gradeProject1765532',
  );
}
